if: commit_message !~ /^(docs|style|chore)(\(.*\))?:/

language: node_js

cache: yarn

node_js:
  - 8.15.0

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: 8.15.0
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
