if: commit_message !~ /^(docs|style|chore)(\(.*\))?:/

language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - 8
  - 10

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
